Adding guide on dev containers
SUSE/bci-docs pull request #14
Opened 2022-06-29 18:49 UTC by mattfarina

Adding docs on VS Code dev containers. Some notes on the post...

1. VS Code is the most dominant editor/IDE but a long shot, according to the [Stack Overflow 2022 survey](https://survey.stackoverflow.co/2022/#section-most-popular-technologies-integrated-development-environment). Writing a post on using the BCIs within that flow targets where many of our users are at.
2. Windows is the most popular primary OS people are using. While Linux comes in second that includes Chrome OS (which makes up a big chunk). A majority of people aren't on GNU/Linux so this offers up a route for them. See [SO 2022 survey on OS](https://survey.stackoverflow.co/2022/#section-most-popular-technologies-operating-system).

2022-06-30 09:57 UTC, dcermak requested changes
Great guide overall! Would you maybe have a screenshot or two at hand to illustrate this?

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +environment.
```suggestion
Visual Studio Code has a feature called [Development Containers](https://code.visualstudio.com/docs/remote/create-dev-container).
This is part of the built-in functionality to work with remote containers. The
SLE Language Stack BCIs make a great choice to use as a development
environment.
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +are on Windows, macOS, or Linux the environment the environment will be the same.
```suggestion
Second, when you have a team of people working on an application,
all developers will have the same environment to work in. Whether they
are on Windows, MacOS, or Linux their environment will be the same.
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +available on your system.
```suggestion
VS Code creates the development containers using the Docker Engine and
it communicates with it over the Docker socket. That means you need a Docker socket
available on your system.
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +directly on your system if you are using Linux.
```suggestion
[Rancher Desktop](https://rancherdesktop.io) is our recommended app for working
with containers. It is available for Windows, MacOS, and Linux. Alternatively,
you can use another tool such as Docker Desktop or the Docker Engine itself
if you are using Linux.
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +guide does not cover handling that situation. {{< /hint >}}
```suggestion
VS Code mounts your code from the local system inside the container. This works
best when the container runtime is on your local system as opposed to remote.
While possible to do this with the container runtime on a remote system, this
guide does not cover running the development container on a remote machine.
{{< /hint >}}
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +## Dev Container Basics
```suggestion
## Development Container Basics
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +VS Code needs some additions installed you can't simply point it at a BCI image.
```suggestion
There are two ways to specify where to get the container from. You can point it
at an image or you can point it at a _Dockerfile_ to build the image from. Since
VS Code needs some additional packages installed you can't simply point it at 
a BCI image.
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +For example, this file could look like:
```suggestion
For example, `devcontainer.json` could look like the following:
```

2022-06-30 09:57 UTC, dcermak commented on content/guides/dev-containers.md
> +## Dev Container Configuration
```suggestion
## Development Container Configuration
```

2022-07-06 18:18 UTC, mattfarina commented on content/guides/dev-containers.md
> +are on Windows, macOS, or Linux the environment the environment will be the same.
@dcermak it's "macOS" See https://www.apple.com/macos/monterey/

2022-07-06 20:20 UTC, mattfarina commented
@dcermak Updated per your feedback. Added images using a method baked in to this theme.

2022-07-07 14:40 UTC, merged