Language and style review
SUSE/BCI-docs pull request #17
Opened 2022-07-05 09:44 UTC by dmpop

2022-07-05 13:35 UTC, dcermak requested changes
Impressive write up! I've just added a few minor comments.

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +registers the running container. This gives access the SUSE Linux
This is technically not correct. The container is not registered at all, because that would count towards the number of subscriptions that you are allowed to consume. `container-suseconnect` merely reuses your credentials and constructs the appropriate repositories from that.

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +the plugin detects the host's SUSE Linux Enterprise Server, it automatically
```suggestion
the plugin finds the host's SUSE Linux Enterprise Server registration credentials, it automatically
```

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +your part.
"on your part" sounds weird to me, but that might be just me.
```suggestion
your side.
```

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +## How to use container-suseconnect on non-SLE hosts or with Podman, Buildah or with nerdctl
Why not capitalize nerdctl as well?

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +_REGISTRATION_CODE_ with your SUSE Connect registration code):
I would suggest to render it as verbatim, as is commonly done in markdown docs. Otherwise it will be displayed in italic, which imho reduces the recognition of that parameter.
```suggestion
`REGISTRATION_CODE` with your SUSE Connect registration code):
```

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +example show how to mount `SCCcredentials` in the current working directory:
```suggestion
example shows how to mount `SCCcredentials` in the current working directory:
```

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +image t avoid inadvertently adding them to the final image. Use secrets instead,
```suggestion
image to avoid inadvertently adding them to the final image. Use secrets instead,
```

2022-07-05 13:35 UTC, dcermak commented on content/guides/container-suseconnect.md
> +image. To do this, put copy of `SCCcredentials`  (and optionally `SUSEConnect`)
```suggestion
image. To do this, put a copy of `SCCcredentials`  (and optionally `SUSEConnect`)
```

2022-07-05 13:46 UTC, dmpop commented on content/guides/container-suseconnect.md
> +## How to use container-suseconnect on non-SLE hosts or with Podman, Buildah or with nerdctl
Because `netctl` is written in lowercase, see https://github.com/containerd/nerdctl

2022-07-05 13:47 UTC, dmpop commented on content/guides/container-suseconnect.md
> +your part.
No, `part` is correct, see https://www.ldoceonline.com/dictionary/on-somebody-s-part-on-the-part-of-somebody

2022-07-05 13:49 UTC, dmpop reviewed
Apply suggestions

2022-07-07 09:56 UTC, dcermak reviewed
LGTM! I have just added two minor suggestions.

2022-07-07 09:56 UTC, dcermak commented on content/guides/container-suseconnect.md
> +`REGISTRATION_CODE` with your SUSE Connect registration code):
I believe it is not referred to as the "SUSE Connect registration code", at least I never heard that term.
```suggestion
`REGISTRATION_CODE` with your SCC registration code)
```

2022-07-07 13:35 UTC, dcermak approved these changes

2022-07-07 13:37 UTC, merged