Correct wording to use "SLE BCI" consistently
SUSE/bci-docs pull request #76
Opened 2023-01-10 12:38 UTC by dirkmueller

SUSE BCI, SLE-BCI, BCI should all be standardized to SLE BCI.
- Leaving out the FAQ as that is going to be moved to suse.com.
- Fixing Busybox -> BusyBox typo

2023-01-11 10:52 UTC, dcermak requested changes
Looks mostly good to me, except for a few tiny issues.

2023-01-11 10:52 UTC, dcermak commented on content/guides/adding-users.adoc
> +This guide will demonstrate how to add users to the SLE BCI Micro and SLE Minimal
This looks wrong, I'd say either "and SLE BCI Minimal" or just "Minimal", but not "SLE Minimal"

2023-01-11 10:52 UTC, dcermak commented on content/guides/adding-users.adoc
> +then consider using the SLE BCI BusyBox image instead. It is even smaller than BCI
```suggestion
then consider using the SLE BCI BusyBox image instead. It is even smaller than SLE BCI
```

2023-01-11 10:52 UTC, dcermak commented on content/guides/adding-users.adoc
> +`--build-arg` parameter as in link:#_Switch_to_using_the_BusyBox_BCI[Switch to
This link is now wrong

2023-01-24 10:06 UTC, dirkmueller commented on content/guides/adding-users.adoc
> +This guide will demonstrate how to add users to the SLE BCI Micro and SLE Minimal
resolved

2023-01-24 10:07 UTC, dirkmueller commented on content/guides/adding-users.adoc
> +`--build-arg` parameter as in link:#_Switch_to_using_the_BusyBox_BCI[Switch to
corrected

2023-01-24 10:25 UTC, dcermak requested changes
The link is still not working.

2023-01-24 10:25 UTC, dcermak commented on content/guides/adding-users.adoc
> +`--build-arg` parameter as in link:#_Switch_to_using_the_SLE_BCI[Switch to
```suggestion
`--build-arg` parameter as in link:#_switch_to_using_the_busybox_sle_bci[Switch to
```

2023-01-24 12:22 UTC, dcermak approved these changes
LGTM, thanks!

2023-01-24 12:23 UTC, merged